name: fuelmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get: ^4.7.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.0.7            # ✅ compatible with Dart 3.4
  google_mobile_ads: ^2.3.0
  hive: ^2.2.3
  shared_preferences: ^2.3.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
